# Generated by Django 2.0.5 on 2018-06-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('dob', models.CharField(blank=True, max_length=12, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=75, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
