# Generated by Django 2.0.5 on 2018-06-22 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADDRESS',
            fields=[
                ('Address_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Zip_Post', models.CharField(max_length=16)),
                ('Address_1', models.CharField(max_length=32)),
                ('Address_2', models.CharField(max_length=32)),
                ('Country', models.CharField(max_length=32)),
                ('State', models.CharField(max_length=32)),
                ('City_Town', models.CharField(max_length=32)),
                ('Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AUTHOR',
            fields=[
                ('AuthorID', models.IntegerField(primary_key=True, serialize=False)),
                ('Bio', models.CharField(max_length=512)),
                ('Lname', models.CharField(max_length=20)),
                ('Fname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('CoverImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('Copies_sold', models.IntegerField(blank=True, null=True)),
                ('Book_description', models.CharField(max_length=1500, null=True)),
                ('Release_date', models.DateField(null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('Book_title', models.CharField(max_length=250, null=True)),
                ('InStock', models.IntegerField(blank=True, null=True)),
                ('AuthorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookDetails.AUTHOR')),
            ],
        ),
        migrations.CreateModel(
            name='BOOK_RATING',
            fields=[
                ('BOOK_RATING_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Five_star_count', models.IntegerField()),
                ('Four_star_count', models.IntegerField()),
                ('Three_star_count', models.IntegerField()),
                ('Two_star_count', models.IntegerField()),
                ('One_star_count', models.IntegerField()),
                ('Zero_star_count', models.IntegerField()),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookDetails.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='CART',
            fields=[
                ('Cart_ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CART_CONTENT',
            fields=[
                ('Cart_contentID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Cart_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookDetails.CART')),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookDetails.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='COMMENT',
            fields=[
                ('CommentID', models.IntegerField(primary_key=True, serialize=False)),
                ('Time_posted', models.DateTimeField()),
                ('Comment_Text', models.CharField(max_length=500, null=True)),
                ('UseNickname', models.NullBooleanField()),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookDetails.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='CREDIT_CARD',
            fields=[
                ('C_card_number', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('CVV', models.CharField(max_length=8)),
                ('Exp_day', models.CharField(max_length=16)),
                ('Exp_month', models.CharField(max_length=16)),
                ('Exp_year', models.CharField(max_length=4)),
                ('Fname', models.CharField(max_length=32)),
                ('Lname', models.CharField(max_length=32)),
                ('Mname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GENRE',
            fields=[
                ('GenreID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PREFERRED_CREDIT_CARD',
            fields=[
                ('PCC_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('C_card_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookDetails.CREDIT_CARD')),
            ],
        ),
        migrations.CreateModel(
            name='PUBLISHER_INFO',
            fields=[
                ('PublisherID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PURCHASE_HISTORY_CONTENT',
            fields=[
                ('PHC_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Time', models.DateTimeField()),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookDetails.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='RATING_HISTORY',
            fields=[
                ('RatingID', models.IntegerField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookDetails.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='RESERVED_CREDIT_CARD',
            fields=[
                ('RCC_ID', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('C_card_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookDetails.CREDIT_CARD')),
            ],
        ),
        migrations.CreateModel(
            name='SAVED_FOR_LATER_CONTENT',
            fields=[
                ('Saved_ContentID', models.IntegerField(primary_key=True, serialize=False)),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookDetails.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('Username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=64)),
                ('Password', models.CharField(max_length=16)),
                ('Lname', models.CharField(max_length=32)),
                ('Fname', models.CharField(max_length=32)),
                ('Nick_name', models.CharField(max_length=32)),
                ('Cart_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookDetails.CART')),
            ],
        ),
        migrations.CreateModel(
            name='USER_HOME_ADDRESS',
            fields=[
                ('Home_address_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookDetails.ADDRESS')),
            ],
        ),
        migrations.CreateModel(
            name='USER_SHIPPING_ADDRESS',
            fields=[
                ('Shipping_address_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookDetails.ADDRESS')),
                ('Username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookDetails.USER')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Home_address_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookDetails.USER_HOME_ADDRESS'),
        ),
        migrations.AddField(
            model_name='user',
            name='Preferred_credit_card_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookDetails.PREFERRED_CREDIT_CARD'),
        ),
        migrations.AddField(
            model_name='saved_for_later_content',
            name='Username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookDetails.USER'),
        ),
        migrations.AddField(
            model_name='reserved_credit_card',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookDetails.USER'),
        ),
        migrations.AddField(
            model_name='rating_history',
            name='Username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookDetails.USER'),
        ),
        migrations.AddField(
            model_name='purchase_history_content',
            name='Username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookDetails.USER'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookDetails.USER'),
        ),
        migrations.AddField(
            model_name='book',
            name='GenreID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookDetails.GENRE'),
        ),
        migrations.AddField(
            model_name='book',
            name='PublisherID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BookDetails.PUBLISHER_INFO'),
        ),
    ]
