# Generated by Django 2.0.5 on 2018-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180606_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
