# Generated by Django 2.0.5 on 2018-06-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180608_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='CoverImage',
            field=models.ImageField(default='book_images/noImage.png', upload_to='book_images/'),
        ),
    ]
