# Generated by Django 2.0.5 on 2018-06-02 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADDRESS',
            fields=[
                ('Address_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Zip_Post', models.CharField(max_length=16)),
                ('Address_1', models.CharField(max_length=32)),
                ('Address_2', models.CharField(max_length=32)),
                ('Country', models.CharField(max_length=32)),
                ('State', models.CharField(max_length=32)),
                ('City_Town', models.CharField(max_length=32)),
                ('Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('num_stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('CoverImage', models.IntegerField()),
                ('Copies_sold', models.IntegerField()),
                ('Book_description', models.CharField(max_length=1500)),
                ('Release_date', models.DateField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='BOOK_RATING',
            fields=[
                ('BOOK_RATING_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Five_star_count', models.IntegerField()),
                ('Four_star_count', models.IntegerField()),
                ('Three_star_count', models.IntegerField()),
                ('Two_star_count', models.IntegerField()),
                ('One_star_count', models.IntegerField()),
                ('Zero_star_count', models.IntegerField()),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='CART',
            fields=[
                ('Cart_ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CART_CONTENT',
            fields=[
                ('Cart_contentID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Cart_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.CART')),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='COMMENT',
            fields=[
                ('CommentID', models.IntegerField(primary_key=True, serialize=False)),
                ('Time_posted', models.DateTimeField()),
                ('Comment_Text', models.CharField(max_length=500)),
                ('UseNickname', models.BooleanField()),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='CREDIT_CARD',
            fields=[
                ('C_card_number', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('CVV', models.IntegerField()),
                ('Exp_day', models.IntegerField()),
                ('Exp_month', models.IntegerField()),
                ('Exp_year', models.IntegerField()),
                ('Fname', models.CharField(max_length=32)),
                ('Lname', models.CharField(max_length=32)),
                ('Mname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GENRE',
            fields=[
                ('GenreID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PREFERRED_CREDIT_CARD',
            fields=[
                ('PCC_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('C_card_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.CREDIT_CARD')),
            ],
        ),
        migrations.CreateModel(
            name='PUBLISHER_INFO',
            fields=[
                ('PublisherID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PURCHASE_HISTORY_CONTENT',
            fields=[
                ('PHC_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Time', models.DateField()),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='RATING_HISTORY',
            fields=[
                ('RatingID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=32)),
                ('Rating', models.IntegerField()),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='RESERVED_CREDIT_CARD',
            fields=[
                ('RCC_ID', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('C_card_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.CREDIT_CARD')),
            ],
        ),
        migrations.CreateModel(
            name='SAVED_FOR_LATER_CONTENT',
            fields=[
                ('Saved_ContentID', models.IntegerField(primary_key=True, serialize=False)),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('Username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=64)),
                ('Password', models.CharField(max_length=16)),
                ('Lname', models.CharField(max_length=32)),
                ('Fname', models.CharField(max_length=32)),
                ('Nick_name', models.CharField(max_length=32)),
                ('Cart_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.CART')),
            ],
        ),
        migrations.CreateModel(
            name='USER_HOME_ADDRESS',
            fields=[
                ('Home_address_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.ADDRESS')),
            ],
        ),
        migrations.CreateModel(
            name='USER_SHIPPING_ADDRESS',
            fields=[
                ('Shipping_address_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.ADDRESS')),
                ('Username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.USER')),
            ],
        ),
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='author',
            name='description',
        ),
        migrations.RemoveField(
            model_name='author',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='author',
            name='education',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
        migrations.AddField(
            model_name='author',
            name='AuthorID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='Bio',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='Fname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='Lname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Home_address_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.USER_HOME_ADDRESS'),
        ),
        migrations.AddField(
            model_name='user',
            name='Preferred_credit_card_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.PREFERRED_CREDIT_CARD'),
        ),
        migrations.AddField(
            model_name='saved_for_later_content',
            name='Username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.USER'),
        ),
        migrations.AddField(
            model_name='reserved_credit_card',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.USER'),
        ),
        migrations.AddField(
            model_name='purchase_history_content',
            name='Username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.USER'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.USER'),
        ),
        migrations.AddField(
            model_name='book',
            name='AuthorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.AUTHOR'),
        ),
        migrations.AddField(
            model_name='book',
            name='GenreID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.GENRE'),
        ),
        migrations.AddField(
            model_name='book',
            name='PublisherID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prof.PUBLISHER_INFO'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.Musician'),
        ),
    ]
