# Generated by Django 2.0.5 on 2018-06-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180623_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
    ]
