# Generated by Django 2.0.5 on 2018-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADDRESS',
            fields=[
                ('Address_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Zip_Post', models.CharField(max_length=16)),
                ('Address_1', models.CharField(max_length=32)),
                ('Address_2', models.CharField(max_length=32)),
                ('Country', models.CharField(max_length=32)),
                ('State', models.CharField(max_length=32)),
                ('City_Town', models.CharField(max_length=32)),
                ('Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AUTHOR',
            fields=[
                ('AuthorID', models.IntegerField(primary_key=True, serialize=False)),
                ('Bio', models.CharField(max_length=512)),
                ('Lname', models.CharField(max_length=20)),
                ('Fname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('GenreID', models.CharField(max_length=13)),
                ('AuthorID', models.IntegerField()),
                ('PublisherID', models.IntegerField()),
                ('CoverImage', models.IntegerField()),
                ('Copies_sold', models.IntegerField()),
                ('Book_description', models.CharField(max_length=1500)),
                ('Release_date', models.DateField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='BOOK_RATING',
            fields=[
                ('BOOK_RATING_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=13)),
                ('Five_star_count', models.IntegerField()),
                ('Four_star_count', models.IntegerField()),
                ('Three_star_count', models.IntegerField()),
                ('Two_star_count', models.IntegerField()),
                ('One_star_count', models.IntegerField()),
                ('Zero_star_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CART',
            fields=[
                ('Cart_ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CART_CONTENT',
            fields=[
                ('Cart_contentID', models.IntegerField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=13)),
                ('Cart_ID', models.CharField(max_length=32)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='COMMENT',
            fields=[
                ('CommentID', models.IntegerField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=13)),
                ('Username', models.CharField(max_length=32)),
                ('Time_posted', models.DateField()),
                ('Comment_Text', models.CharField(max_length=500)),
                ('UseNickname', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CREDIT_CARD',
            fields=[
                ('C_card_number', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('CVV', models.CharField(max_length=8)),
                ('Exp_day', models.CharField(max_length=16)),
                ('Exp_month', models.CharField(max_length=16)),
                ('Exp_year', models.CharField(max_length=4)),
                ('Fname', models.CharField(max_length=32)),
                ('Lname', models.CharField(max_length=32)),
                ('Mname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GENRE',
            fields=[
                ('GenreID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PREFERRED_CREDIT_CARD',
            fields=[
                ('PCC_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('C_card_number', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='PUBLISHER_INFO',
            fields=[
                ('PublisherID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PURCHASE_HISTORY_CONTENT',
            fields=[
                ('PHC_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=32)),
                ('ISBN', models.CharField(max_length=13)),
                ('Quantity', models.IntegerField()),
                ('Time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RATING_HISTORY',
            fields=[
                ('RatingID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=13)),
                ('Username', models.CharField(max_length=32)),
                ('Rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RESERVED_CREDIT_CARD',
            fields=[
                ('RCC_ID', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('C_card_number', models.CharField(max_length=24)),
                ('Username', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SAVED_FOR_LATER_CONTENT',
            fields=[
                ('Saved_ContentID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=32)),
                ('ISBN', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('Username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Home_address_ID', models.IntegerField()),
                ('Preferred_credit_card_ID', models.CharField(max_length=24)),
                ('Cart_ID', models.CharField(max_length=32)),
                ('Email', models.CharField(max_length=64)),
                ('Password', models.CharField(max_length=16)),
                ('Lname', models.CharField(max_length=32)),
                ('Fname', models.CharField(max_length=32)),
                ('Nick_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='USER_HOME_ADDRESS',
            fields=[
                ('Home_address_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='USER_SHIPPING_ADDRESS',
            fields=[
                ('Shipping_address_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address_ID', models.IntegerField()),
                ('Username', models.CharField(max_length=32)),
            ],
        ),
    ]
