# Generated by Django 2.0.5 on 2018-06-27 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ADDRESS',
            fields=[
                ('Address_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Zip_Post', models.CharField(max_length=16)),
                ('Address_1', models.CharField(max_length=32)),
                ('Address_2', models.CharField(max_length=32)),
                ('Country', models.CharField(max_length=32)),
                ('State', models.CharField(max_length=32)),
                ('City_Town', models.CharField(max_length=32)),
                ('Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AUTHOR',
            fields=[
                ('AuthorID', models.IntegerField(primary_key=True, serialize=False)),
                ('Bio', models.CharField(max_length=512)),
                ('Lname', models.CharField(max_length=20)),
                ('Fname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('CoverImage', models.ImageField(default='book_images/noImage.png', upload_to='book_images/')),
                ('Copies_sold', models.IntegerField(default=0)),
                ('Book_description', models.CharField(max_length=1500, null=True)),
                ('Release_date', models.DateField(null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('Title', models.CharField(max_length=128, null=True)),
                ('AuthorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.AUTHOR')),
            ],
        ),
        migrations.CreateModel(
            name='BOOK_RATING',
            fields=[
                ('Book_rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Five_star_count', models.IntegerField()),
                ('Four_star_count', models.IntegerField()),
                ('Three_star_count', models.IntegerField()),
                ('Two_star_count', models.IntegerField()),
                ('One_star_count', models.IntegerField()),
                ('Zero_star_count', models.IntegerField()),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='CART',
            fields=[
                ('Cart_ID', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CART_CONTENT',
            fields=[
                ('Cart_contentID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Cart_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.CART')),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='COMMENT',
            fields=[
                ('CommentID', models.IntegerField(primary_key=True, serialize=False)),
                ('Time_posted', models.DateTimeField()),
                ('Comment_Text', models.CharField(max_length=500)),
                ('UseNickname', models.NullBooleanField()),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='CREDIT_CARD',
            fields=[
                ('C_card_number', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('CVV', models.CharField(max_length=8)),
                ('Exp_day', models.CharField(max_length=2)),
                ('Exp_month', models.CharField(max_length=2)),
                ('Exp_year', models.CharField(max_length=4)),
                ('Fname', models.CharField(max_length=32)),
                ('Lname', models.CharField(max_length=32)),
                ('Mname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GENRE',
            fields=[
                ('GenreID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=32)),
                ('Description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PREFERRED_CREDIT_CARD',
            fields=[
                ('PCC_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('C_card_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.CREDIT_CARD')),
            ],
        ),
        migrations.CreateModel(
            name='PUBLISHER_INFO',
            fields=[
                ('PublisherID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PURCHASE_HISTORY_CONTENT',
            fields=[
                ('PHC_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('Time', models.DateTimeField()),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='RATING_HISTORY',
            fields=[
                ('RatingID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='RESERVED_CREDIT_CARD',
            fields=[
                ('RCC_ID', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('C_card_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.CREDIT_CARD')),
            ],
        ),
        migrations.CreateModel(
            name='SAVED_FOR_LATER_CONTENT',
            fields=[
                ('Saved_ContentID', models.IntegerField(primary_key=True, serialize=False)),
                ('ISBN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('ProfileID', models.AutoField(primary_key=True, serialize=False)),
                ('Nick_name', models.CharField(blank=True, default='', max_length=32)),
                ('AuthUser_ID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Cart_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.CART')),
            ],
        ),
        migrations.CreateModel(
            name='USER_HOME_ADDRESS',
            fields=[
                ('Home_address_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Address_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.ADDRESS')),
            ],
        ),
        migrations.CreateModel(
            name='USER_SHIPPING_ADDRESS',
            fields=[
                ('Shipping_address_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.ADDRESS')),
                ('ProfileID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.USER')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Home_address_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.USER_HOME_ADDRESS'),
        ),
        migrations.AddField(
            model_name='user',
            name='Preferred_credit_card_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.PREFERRED_CREDIT_CARD'),
        ),
        migrations.AddField(
            model_name='saved_for_later_content',
            name='ProfileID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.USER'),
        ),
        migrations.AddField(
            model_name='reserved_credit_card',
            name='ProfileID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.USER'),
        ),
        migrations.AddField(
            model_name='rating_history',
            name='ProfileID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.USER'),
        ),
        migrations.AddField(
            model_name='purchase_history_content',
            name='ProfileID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.USER'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ProfileID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.USER'),
        ),
        migrations.AddField(
            model_name='book',
            name='GenreID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.GENRE'),
        ),
        migrations.AddField(
            model_name='book',
            name='PublisherID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.PUBLISHER_INFO'),
        ),
    ]
