# Generated by Django 2.0.5 on 2018-07-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20180701_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserved_credit_card',
            name='RCC_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
