# Generated by Django 2.0.5 on 2018-06-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
