# Generated by Django 2.0.5 on 2018-06-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180623_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
        migrations.RemoveField(
            model_name='books',
            name='image',
        ),
    ]
