# Generated by Django 2.0.5 on 2018-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180623_0511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
